import { precacheAndRoute, cleanupOutdatedCaches } from "workbox-precaching";
import { clientsClaim } from "workbox-core";

declare let self: ServiceWorkerGlobalScope;

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});
clientsClaim();
cleanupOutdatedCaches();

// Precache all assets generated by vite
// @ts-ignore
precacheAndRoute(self.__WB_MANIFEST);

// Handle Push Notifications
self.addEventListener("push", (event) => {
  let data = { title: "New Notification", body: "", url: "/" };

  if (event.data) {
    try {
      data = event.data.json();
    } catch (e) {
      data.body = event.data.text();
    }
  }

  const options = {
    body: data.body,
    icon: "/splitify-logo.png", // Ensure this file exists in /public
    badge: "/splitify-logo.png",
    data: { url: data.url || "/" },
    vibrate: [100, 50, 100],
  };

  event.waitUntil(self.registration.showNotification(data.title, options));
});

// Handle Notification Click
self.addEventListener("notificationclick", (event) => {
  event.notification.close();

  event.waitUntil(
    self.clients.matchAll({ type: "window" }).then((clientList) => {
      // If a window is already open, focus it
      for (const client of clientList) {
        if (client.url === "/" && "focus" in client) return client.focus();
      }
      // Otherwise open a new window
      if (self.clients.openWindow)
        return self.clients.openWindow(event.notification.data.url);
    }),
  );
});
